export const TRANSPARENT = '';
export type PixelFrame = string[];
export interface DitherdeckProject { name:string; size:number; fps:number; frames:PixelFrame[]; palette:string[] }

export const createFrame = (size:number):PixelFrame => Array(size * size).fill(TRANSPARENT);
export function setPixel(frame:PixelFrame,size:number,x:number,y:number,color:string):PixelFrame { if(x<0||y<0||x>=size||y>=size)return frame;const next=frame.slice();next[y*size+x]=color;return next; }
export function floodFill(frame:PixelFrame,size:number,startX:number,startY:number,color:string):PixelFrame { if(startX<0||startY<0||startX>=size||startY>=size)return frame;const target=frame[startY*size+startX];if(target===color)return frame;const next=frame.slice();const stack:Array<[number,number]>=[[startX,startY]];while(stack.length){const [x,y]=stack.pop()!;if(x<0||y<0||x>=size||y>=size)continue;const index=y*size+x;if(next[index]!==target)continue;next[index]=color;stack.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]);}return next; }
export function resizeFrames(frames:PixelFrame[],oldSize:number,newSize:number):PixelFrame[]{return frames.map(frame=>{const next=createFrame(newSize);const overlap=Math.min(oldSize,newSize);for(let y=0;y<overlap;y+=1)for(let x=0;x<overlap;x+=1)next[y*newSize+x]=frame[y*oldSize+x];return next;});}
export function normalizeProject(raw:Partial<DitherdeckProject>,defaultName='untitled sprite'):DitherdeckProject {const allowed=[8,12,16,24,32];const size=allowed.includes(Number(raw.size))?Number(raw.size):16;const frames=Array.isArray(raw.frames)&&raw.frames.length?raw.frames.slice(0,64).map(frame=>createFrame(size).map((_,i)=>typeof frame[i]==='string'?frame[i]:'')):[createFrame(size)];const palette=Array.isArray(raw.palette)?raw.palette.filter(color=>/^#[0-9a-f]{6}$/i.test(color)).slice(0,16):[];return{name:String(raw.name||defaultName).slice(0,60),size,fps:Math.min(24,Math.max(1,Number(raw.fps)||8)),frames,palette:palette.length?palette:['#18222d','#f4e8cf','#ff4f88','#ffc857','#4cc9a4','#4f7cff']};}
