"use strict";(()=>{var k="karmolab_home_prefs",f=["today","live","cta"];function x(){try{let d=localStorage.getItem(k);if(!d)return{version:2,order:[],hidden:[...f],name:""};let s=JSON.parse(d),g=Array.isArray(s.order)?s.order.filter(m=>typeof m=="string"):[],h=Array.isArray(s.hidden)?s.hidden.filter(m=>typeof m=="string"):[],v=g.length>0||h.length>0||typeof s.name=="string"&&s.name.trim().length>0,w=s.version!==2&&!v;return{version:2,order:g,hidden:w?[...f]:h,name:typeof s.name=="string"?s.name.slice(0,20):""}}catch{return{version:2,order:[],hidden:[...f],name:""}}}function u(d){return x().hidden.indexOf(d)>=0}(function(){let d=(e,o)=>Toolbox.switchPage(e,o),s=()=>Toolbox.mountHomeDecor(),g=()=>Toolbox.getTools(),h=()=>Toolbox.toolCountsOnce(),v=e=>Toolbox.whenApiBase(e);function w(){let e=document.createElement("div");e.className="landing-page",e.id="page-home",s();let o=document.createElement("div");o.className="landing-hero",o.innerHTML=`
            <h1 class="landing-title">KarmoLab</h1>
            <p class="landing-tagline">\uC0B6\uC744 \uC11E\uACE0 \uC220\uC744 \uBC14\uAFC0 \uC2DC\uAC04</p>
        `,e.appendChild(o);let a=document.createElement("div");a.className="landing-palette",e.appendChild(a),typeof window<"u"&&window.KarmoPalette&&window.KarmoPalette.mountInline(a);let n=document.createElement("div");if(n.className="landing-today",n.id="homeToday",n.dataset.block="today",n.hidden=u("today"),e.appendChild(n),Toolbox.ensureScript&&!n.hidden){n.dataset.reserving="1";let p=()=>{delete n.dataset.reserving};Toolbox.ensureScript("root/today").then(()=>{window.KarmoToday?window.KarmoToday.mount(n):p()}).catch(p)}let r=document.createElement("div");r.className="landing-cta",r.dataset.block="cta",r.hidden=u("cta"),r.innerHTML=`
            <div class="landing-cta-grid">
                <button type="button" class="landing-cta-card" onclick="Toolbox.switchPage('favorites')">
                    <span class="landing-cta-card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg></span>
                    <span class="landing-cta-card-title">\uC990\uACA8\uCC3E\uAE30</span>
                </button>
                <a class="landing-cta-card" href="/karmolab/t/">
                    <span class="landing-cta-card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h16M4 12h16M4 18h10"/></svg></span>
                    <span class="landing-cta-card-title">\uB3C4\uAD6C \uBAA9\uB85D</span>
                </a>
                <button type="button" class="landing-cta-card" onclick="Toolbox.switchPage('community')">
                    <span class="landing-cta-card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h16v10H9l-4 3.5V16H4z"/><path d="M8 10h8M8 13h5"/></svg></span>
                    <span class="landing-cta-card-title">\uCEE4\uBBA4\uB2C8\uD2F0</span>
                </button>
                <button type="button" class="landing-cta-card" onclick="Toolbox.switchPage('arcade')">
                    <span class="landing-cta-card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="7" width="18" height="11" rx="4"/><path d="M7.5 11v3M6 12.5h3"/><path d="M16 12h.01M18 14.5h.01"/></svg></span>
                    <span class="landing-cta-card-title">\uC624\uB77D\uC2E4</span>
                </button>
                <button type="button" class="landing-cta-card" onclick="Toolbox.switchPage('docs')">
                    <span class="landing-cta-card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg></span>
                    <span class="landing-cta-card-title">\uBB38\uC11C</span>
                </button>
            </div>
        `,e.appendChild(r);let t=document.createElement("div");t.className="landing-live",t.id="homeLive",t.dataset.block="live",t.hidden=u("live"),e.appendChild(t),Toolbox.ensureScript&&!t.hidden&&(t.dataset.reserving="1",Toolbox.ensureScript("root/live").then(()=>{window.KarmoLive?window.KarmoLive.mount(t):delete t.dataset.reserving}).catch(()=>{delete t.dataset.reserving}));let l=document.createElement("div");l.className="landing-pulse",l.id="homePulse",l.dataset.block="pulse",l.hidden=u("pulse"),e.appendChild(l),y(l);let c=document.createElement("div");return c.className="hp-slot",e.appendChild(c),Toolbox.ensureScript&&Toolbox.ensureScript("root/home-prefs").then(()=>window.KarmoHomePrefs&&window.KarmoHomePrefs.install(e)).catch(()=>{}),e}function m(e){return String(e??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function b(e){let o=g().find(n=>n.id===e);if(o&&o.title)return o.title;let a=typeof window<"u"&&window.KARMOLAB_LAZY_META_BY_ID||{};return a[e]&&a[e].title||null}async function y(e){let o=typeof window<"u"&&window.KarmoAccount&&window.KarmoAccount.apiBase||"";if(!o)return;e.dataset.reserving="1";let a=()=>{delete e.dataset.reserving},n;try{let i=await fetch(o+"/kl/tools/stats");if(!i.ok){a();return}n=await i.json()}catch{a();return}let r=n&&n.pulse||{},t=n&&n.visits||{},l=(n.tools||[]).filter(i=>i.recent>0&&b(i.toolId)).slice(0,6).map(i=>i.toolId);if(l.length&&typeof window<"u"&&window.KarmoPalette&&window.KarmoPalette.setPopular(l),!e.isConnected){a();return}if(!r.opensTotal&&!t.total){a();return}let c=i=>Number(i||0).toLocaleString("ko-KR");if(!t.total){a();return}e.innerHTML='<p class="landing-pulse-line"><span class="landing-pulse-stat"><span class="landing-pulse-k">Today</span><b>'+c(t.today)+'</b></span><span class="landing-pulse-stat"><span class="landing-pulse-k">Total</span><b>'+c(t.total)+'</b></span><button type="button" class="landing-pulse-all" data-open-plaza>\uC804\uBD80 \uBCF4\uAE30 \u2192</button></p>';let p=e.querySelector("[data-open-plaza]");p&&(p.onclick=()=>d("plaza"))}window.KarmoHomePage={build:w}})();})();
