// KarmoLab Tauri build script.
//
// TASK-KL-063 (KAR-022 child): ACL 4-source 중복을 단일 정본(`acl.toml`)에서 파생.
// 빌드 시 acl.toml → (1) $OUT_DIR/acl_handler.rs  (2) permissions/_generated/*.toml.
// 파생 toml 은 tauri_build::try_build 가 ACL 로 읽으므로 *그 호출 전에* 써야 한다.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct AclManifest {
    group: Vec<AclGroup>,
}

#[derive(serde::Deserialize)]
struct AclGroup {
    name: String,
    identifier: String,
    description: String,
    commands: Vec<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=acl.toml");

    let raw = fs::read_to_string("acl.toml").expect("acl.toml 읽기 실패");
    let manifest: AclManifest = toml::from_str(&raw).expect("acl.toml 파싱 실패");

    // --- 무결성: command 이름 전역 유일 (한 command 가 두 그룹 = ACL 모호) ---
    let mut seen: BTreeMap<&str, &str> = BTreeMap::new();
    for group in &manifest.group {
        for cmd in &group.commands {
            if let Some(prev) = seen.insert(cmd.as_str(), group.name.as_str()) {
                panic!(
                    "acl.toml: command '{}' 가 그룹 '{}' 와 '{}' 에 중복 — 한 command = 한 group",
                    cmd, prev, group.name
                );
            }
        }
    }

    // --- (1) generate_handler! include 파생 ---
    // lib.rs scope 에서 모든 command fn 이 `use` 되어 있으므로 bare ident 로 충분.
    let mut idents: Vec<&str> = seen.keys().copied().collect();
    idents.sort_unstable();
    let handler_src = format!(
        "// @generated by build.rs from acl.toml — DO NOT EDIT.\n\
         tauri::generate_handler![\n{}\n]\n",
        idents
            .iter()
            .map(|c| format!("    {c}"))
            .collect::<Vec<_>>()
            .join(",\n")
    );
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR 미설정");
    fs::write(Path::new(&out_dir).join("acl_handler.rs"), handler_src)
        .expect("acl_handler.rs 쓰기 실패");

    // --- (2) permissions/_generated/<group>.toml 파생 ---
    // Tauri 가 permissions/**/*.toml 을 ACL 로 스캔. gitignore 생성물.
    // **IDEMPOTENT 필수 (KL-064)**: 옛 코드는 매 빌드 remove_dir_all + 재write
    // → 내용 동일해도 파일 mtime/존재 변동 → `tauri dev` 파일워처가 변경
    // 감지 → 리빌드 → build.rs 재실행 → 또 변동 → *무한 리빌드 루프*
    // (창이 영원히 안 뜸, KL-063 이후 미발견). 해결: 내용이 *바뀐 파일만*
    // write, 사라진 그룹 파일만 제거. 동일하면 디스크 무변동 = 워처 침묵.
    let gen_dir = Path::new("permissions/_generated");
    fs::create_dir_all(gen_dir).expect("permissions/_generated 생성 실패");

    let mut expected: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for group in &manifest.group {
        let allow_list = group
            .commands
            .iter()
            .map(|c| format!("  \"{c}\","))
            .collect::<Vec<_>>()
            .join("\n");
        let toml_src = format!(
            "# @generated by build.rs from acl.toml (TASK-KL-063) — DO NOT EDIT.\n\
             # 정본 = ../../acl.toml [[group]] name = \"{name}\".\n\n\
             [[permission]]\n\
             identifier = \"{ident}\"\n\
             description = \"{desc}\"\n\
             commands.allow = [\n{allow}\n]\n",
            name = group.name,
            ident = group.identifier,
            desc = group.description.replace('\\', "\\\\").replace('"', "\\\""),
            allow = allow_list,
        );
        let fname = format!("{}.toml", group.name);
        let path = gen_dir.join(&fname);
        expected.insert(fname);
        // 내용 동일 시 write 생략 (mtime 도 안 건드림 → 워처 침묵).
        let unchanged = fs::read_to_string(&path)
            .map(|cur| cur == toml_src)
            .unwrap_or(false);
        if !unchanged {
            fs::write(&path, toml_src).expect("그룹 toml 쓰기 실패");
        }
    }
    // acl.toml 에서 사라진 그룹의 stale .toml 만 제거 (전체 wipe X).
    if let Ok(entries) = fs::read_dir(gen_dir) {
        for e in entries.flatten() {
            let n = e.file_name().to_string_lossy().into_owned();
            if n.ends_with(".toml") && !expected.contains(&n) {
                let _ = fs::remove_file(e.path());
            }
        }
    }

    // --- (3) Tauri build (파생 toml 이 디스크에 있는 상태로 호출) ---
    // .commands(&[..]) 미지정: per-command autogenerated perm 불요 — 그룹 toml 이
    // 모든 command 를 commands.allow 로 커버 (desktop_notify 도 desktop-notify 그룹 흡수).
    tauri_build::try_build(tauri_build::Attributes::new())
        .expect("failed to run tauri-build");
}
