// KarmoLab Tauri build script.
//
// TASK-KL-063 (KAR-022 child): ACL 4-source 중복을 단일 정본(`acl.toml`)에서 파생.
// 빌드 시 acl.toml → (1) $OUT_DIR/acl_handler.rs  (2) permissions/_generated/*.toml.
// 파생 toml 은 tauri_build::try_build 가 ACL 로 읽으므로 *그 호출 전에* 써야 한다.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct AclManifest {
    group: Vec<AclGroup>,
}

#[derive(serde::Deserialize)]
struct AclGroup {
    name: String,
    identifier: String,
    description: String,
    commands: Vec<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=acl.toml");

    let raw = fs::read_to_string("acl.toml").expect("acl.toml 읽기 실패");
    let manifest: AclManifest = toml::from_str(&raw).expect("acl.toml 파싱 실패");

    // --- 무결성: command 이름 전역 유일 (한 command 가 두 그룹 = ACL 모호) ---
    let mut seen: BTreeMap<&str, &str> = BTreeMap::new();
    for group in &manifest.group {
        for cmd in &group.commands {
            if let Some(prev) = seen.insert(cmd.as_str(), group.name.as_str()) {
                panic!(
                    "acl.toml: command '{}' 가 그룹 '{}' 와 '{}' 에 중복 — 한 command = 한 group",
                    cmd, prev, group.name
                );
            }
        }
    }

    // --- (1) generate_handler! include 파생 ---
    // lib.rs scope 에서 모든 command fn 이 `use` 되어 있으므로 bare ident 로 충분.
    let mut idents: Vec<&str> = seen.keys().copied().collect();
    idents.sort_unstable();
    let handler_src = format!(
        "// @generated by build.rs from acl.toml — DO NOT EDIT.\n\
         tauri::generate_handler![\n{}\n]\n",
        idents
            .iter()
            .map(|c| format!("    {c}"))
            .collect::<Vec<_>>()
            .join(",\n")
    );
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR 미설정");
    fs::write(Path::new(&out_dir).join("acl_handler.rs"), handler_src)
        .expect("acl_handler.rs 쓰기 실패");

    // --- (2) permissions/_generated/<group>.toml 파생 ---
    // Tauri 가 permissions/**/*.toml 을 ACL 로 스캔. autogenerated/ (Tauri 자체생성)
    // 와 같은 패턴의 *생성물 디렉토리* — gitignore, 매 빌드 재생성.
    let gen_dir = Path::new("permissions/_generated");
    if gen_dir.exists() {
        fs::remove_dir_all(gen_dir).expect("permissions/_generated 정리 실패");
    }
    fs::create_dir_all(gen_dir).expect("permissions/_generated 생성 실패");

    for group in &manifest.group {
        let allow_list = group
            .commands
            .iter()
            .map(|c| format!("  \"{c}\","))
            .collect::<Vec<_>>()
            .join("\n");
        let toml_src = format!(
            "# @generated by build.rs from acl.toml (TASK-KL-063) — DO NOT EDIT.\n\
             # 정본 = ../../acl.toml [[group]] name = \"{name}\".\n\n\
             [[permission]]\n\
             identifier = \"{ident}\"\n\
             description = \"{desc}\"\n\
             commands.allow = [\n{allow}\n]\n",
            name = group.name,
            ident = group.identifier,
            desc = group.description.replace('\\', "\\\\").replace('"', "\\\""),
            allow = allow_list,
        );
        fs::write(gen_dir.join(format!("{}.toml", group.name)), toml_src)
            .expect("그룹 toml 쓰기 실패");
    }

    // --- (3) Tauri build (파생 toml 이 디스크에 있는 상태로 호출) ---
    // .commands(&[..]) 미지정: per-command autogenerated perm 불요 — 그룹 toml 이
    // 모든 command 를 commands.allow 로 커버 (desktop_notify 도 desktop-notify 그룹 흡수).
    tauri_build::try_build(tauri_build::Attributes::new())
        .expect("failed to run tauri-build");
}
