/**
 * 이모지 찾기 (TASK-KL-088)
 *
 * 이모지는 이름이 영어라 「웃는 얼굴」 로는 안 잡힌다. 그래서 항목마다 **한국어 검색어**를 붙인다 —
 * 표의 값이 목록 길이가 아니라 「찾아지느냐」 에 있기 때문이다.
 */
(function (): void {
  /** [문자, 이름, 검색 키워드] */
  const E: Record<string, Array<[string, string, string]>> = {
    표정: [
      ['😀', '활짝 웃음', 'smile 웃음 기쁨 하하'],
      ['😃', '웃는 얼굴', 'smile 웃음 반가움'],
      ['😄', '눈웃음', 'smile 웃음 신남'],
      ['😁', '이 드러낸 웃음', 'grin 웃음 씨익'],
      ['😆', '폭소', 'laugh 웃음 빵터짐'],
      ['😅', '식은땀 웃음', 'sweat 민망 어색 웃음'],
      ['🤣', '데굴데굴 웃음', 'rofl 폭소 ㅋㅋㅋ'],
      ['😂', '눈물 나게 웃음', 'joy 폭소 ㅋㅋ 눈물'],
      ['🙂', '살짝 미소', 'slight smile 미소'],
      ['🙃', '뒤집힌 얼굴', 'upside down 반어 비꼼'],
      ['😉', '윙크', 'wink 윙크'],
      ['😊', '수줍은 미소', 'blush 뿌듯 흐뭇'],
      ['😇', '천사', 'angel 착함 순수'],
      ['🥰', '하트 얼굴', 'love 사랑 애정'],
      ['😍', '하트 눈', 'heart eyes 반함 사랑'],
      ['😘', '뽀뽀', 'kiss 키스 사랑'],
      ['😋', '맛있다', 'yum 맛있 냠냠'],
      ['😜', '메롱 윙크', 'tongue 장난'],
      ['🤪', '광대', 'zany 미친 신남'],
      ['🤨', '의심', 'raised eyebrow 의심 뭐지'],
      ['🧐', '외알안경', 'monocle 관찰 분석'],
      ['🤓', '너드', 'nerd 공부 안경'],
      ['😎', '선글라스', 'cool 멋짐 여유'],
      ['🥳', '파티', 'party 축하 생일'],
      ['😏', '능글', 'smirk 씨익 능글'],
      ['😒', '시큰둥', 'unamused 심드렁 노잼'],
      ['😞', '실망', 'disappointed 낙담'],
      ['😔', '풀죽음', 'pensive 시무룩'],
      ['😟', '걱정', 'worried 근심'],
      ['😕', '떨떠름', 'confused 애매'],
      ['🙁', '살짝 찡그림', 'frown 아쉬움'],
      ['😣', '끙끙', 'persevere 힘듦'],
      ['😖', '괴로움', 'confounded 곤란'],
      ['😫', '지침', 'tired 피곤 지침'],
      ['😩', '힘듦', 'weary 힘듦 하소연'],
      ['🥺', '초롱초롱', 'pleading 부탁 애원'],
      ['😢', '눈물', 'cry 슬픔 울음'],
      ['😭', '엉엉', 'sob 대성통곡 슬픔'],
      ['😤', '씩씩', 'triumph 화남 콧김'],
      ['😠', '화남', 'angry 분노'],
      ['😡', '분노', 'rage 빡침 화'],
      ['🤬', '욕설', 'cursing 욕 분노'],
      ['🤯', '멘붕', 'mind blown 충격 폭발'],
      ['😳', '당황', 'flushed 부끄 놀람'],
      ['🥵', '더움', 'hot 더위 땀'],
      ['🥶', '추움', 'cold 추위 얼음'],
      ['😱', '비명', 'scream 공포 놀람'],
      ['😨', '겁먹음', 'fearful 무서움'],
      ['😰', '식은땀', 'anxious 불안'],
      ['😥', '아쉬움', 'sad relieved 안도 아쉬움'],
      ['😓', '진땀', 'downcast sweat 힘듦'],
      ['🤗', '안아주기', 'hug 포옹 환영'],
      ['🤔', '고민', 'thinking 생각 흠'],
      ['🤭', '입가림', 'hand over mouth 웃음참기'],
      ['🤫', '쉿', 'shush 조용'],
      ['🤥', '거짓말', 'lying 피노키오'],
      ['😐', '무표정', 'neutral 무덤덤'],
      ['😑', '띠용', 'expressionless 어이없음'],
      ['😶', '말없음', 'no mouth 침묵'],
      ['😴', '잠', 'sleep 자는중 zzz'],
      ['🤤', '침', 'drooling 군침'],
      ['😪', '졸림', 'sleepy 졸음'],
      ['🤒', '아픔', 'sick 감기 열'],
      ['🤢', '메스꺼움', 'nauseated 역겨움'],
      ['🤮', '토함', 'vomit 구토'],
      ['🥴', '어질', 'woozy 취함 어지러움'],
      ['😵', '기절', 'dizzy 뻗음'],
      ['🤠', '카우보이', 'cowboy 서부'],
      ['🫠', '녹음', 'melting 녹아내림 더위'],
      ['🫡', '경례', 'salute 알겠습니다 충성'],
      ['🫥', '점선 얼굴', 'dotted 투명 존재감'],
      ['💀', '해골', 'skull 죽음 ㅋㅋ'],
      ['👻', '유령', 'ghost 귀신 할로윈'],
      ['👽', '외계인', 'alien 우주인'],
      ['🤖', '로봇', 'robot 봇 AI'],
      ['💩', '똥', 'poop 응가']
    ],
    손짓: [
      ['👍', '따봉', 'thumbs up 좋아요 굿'],
      ['👎', '싫어요', 'thumbs down 별로'],
      ['👌', '오케이', 'ok 좋음'],
      ['🤌', '손끝 모음', 'pinched 이탈리아'],
      ['✌️', '브이', 'victory 브이 평화'],
      ['🤞', '행운 빌기', 'crossed fingers 행운'],
      ['🤟', '사랑해', 'love you 수화'],
      ['🤘', '락', 'rock 메탈'],
      ['🤙', '전화해', 'call me 샤카'],
      ['👋', '인사', 'wave 안녕 손흔들기'],
      ['🙌', '만세', 'raising hands 환호'],
      ['👏', '박수', 'clap 짝짝짝'],
      ['🙏', '기도', 'pray 부탁 감사'],
      ['💪', '힘', 'muscle 근육 파이팅'],
      ['🫰', '손가락 하트', 'finger heart 하트'],
      ['🤝', '악수', 'handshake 협력 계약'],
      ['✍️', '쓰기', 'writing 서명'],
      ['👀', '눈', 'eyes 주목 봄']
    ],
    마음: [
      ['❤️', '빨간 하트', 'heart 사랑'],
      ['🧡', '주황 하트', 'orange heart'],
      ['💛', '노란 하트', 'yellow heart'],
      ['💚', '초록 하트', 'green heart'],
      ['💙', '파란 하트', 'blue heart'],
      ['💜', '보라 하트', 'purple heart'],
      ['🖤', '검은 하트', 'black heart'],
      ['🤍', '흰 하트', 'white heart'],
      ['💔', '깨진 하트', 'broken heart 실연'],
      ['💕', '두 하트', 'two hearts 애정'],
      ['💖', '반짝 하트', 'sparkling heart'],
      ['💯', '백점', '100 완벽 인정'],
      ['✨', '반짝', 'sparkles 반짝임 새로움'],
      ['🔥', '불', 'fire 대박 핫함'],
      ['⭐', '별', 'star 즐겨찾기'],
      ['🌟', '빛나는 별', 'glowing star'],
      ['💥', '쾅', 'boom 충돌 폭발'],
      ['💫', '어지러움', 'dizzy 반짝'],
      ['🎉', '축하', 'tada 파티 축하'],
      ['🎊', '색종이', 'confetti 축하']
    ],
    사물: [
      ['💻', '노트북', 'laptop 컴퓨터 개발'],
      ['🖥️', '데스크톱', 'desktop 모니터'],
      ['📱', '휴대폰', 'phone 스마트폰'],
      ['⌨️', '키보드', 'keyboard 타자'],
      ['🖱️', '마우스', 'mouse'],
      ['💾', '플로피', 'floppy 저장'],
      ['📀', '디스크', 'disc CD DVD'],
      ['🔋', '배터리', 'battery 충전'],
      ['🔌', '플러그', 'plug 전원'],
      ['📷', '카메라', 'camera 사진'],
      ['🎧', '헤드폰', 'headphone 음악'],
      ['🎮', '게임패드', 'game 게임 컨트롤러'],
      ['📚', '책', 'books 공부 독서'],
      ['📝', '메모', 'memo 노트 필기'],
      ['📌', '핀', 'pin 고정 중요'],
      ['📎', '클립', 'paperclip 첨부'],
      ['🔍', '돋보기', 'search 검색 확대'],
      ['🔒', '자물쇠', 'lock 잠금 보안'],
      ['🔑', '열쇠', 'key 키 비밀번호'],
      ['💡', '전구', 'bulb 아이디어'],
      ['🧭', '나침반', 'compass 방향'],
      ['⏰', '알람시계', 'alarm 시간'],
      ['⌛', '모래시계', 'hourglass 대기'],
      ['💰', '돈주머니', 'money 돈'],
      ['💸', '날아가는 돈', 'money wings 지출'],
      ['🛒', '카트', 'cart 쇼핑'],
      ['🎁', '선물', 'gift 프레젠트'],
      ['🧪', '시험관', 'test tube 실험'],
      ['⚙️', '톱니바퀴', 'gear 설정 엔진'],
      ['🔧', '렌치', 'wrench 수리 도구'],
      ['🔨', '망치', 'hammer 빌드'],
      ['🧹', '빗자루', 'broom 정리 청소'],
      ['🗑️', '휴지통', 'trash 삭제'],
      ['📦', '상자', 'package 패키지 배포']
    ],
    자연: [
      ['🌞', '해', 'sun 태양 맑음'],
      ['🌙', '달', 'moon 밤'],
      ['☁️', '구름', 'cloud 흐림'],
      ['🌧️', '비', 'rain 비'],
      ['⛈️', '천둥', 'thunder 뇌우'],
      ['❄️', '눈', 'snow 겨울'],
      ['🌈', '무지개', 'rainbow'],
      ['🌊', '파도', 'wave 바다'],
      ['🌸', '벚꽃', 'blossom 봄 꽃'],
      ['🌻', '해바라기', 'sunflower 여름'],
      ['🍁', '단풍', 'maple 가을'],
      ['🌱', '새싹', 'seedling 시작 성장'],
      ['🌵', '선인장', 'cactus'],
      ['🐶', '강아지', 'dog 개'],
      ['🐱', '고양이', 'cat 야옹'],
      ['🐰', '토끼', 'rabbit'],
      ['🦊', '여우', 'fox'],
      ['🐻', '곰', 'bear'],
      ['🐼', '판다', 'panda'],
      ['🐧', '펭귄', 'penguin'],
      ['🐢', '거북', 'turtle 느림'],
      ['🐍', '뱀', 'snake 파이썬'],
      ['🦄', '유니콘', 'unicorn 유니콘'],
      ['🐝', '벌', 'bee'],
      ['🦋', '나비', 'butterfly']
    ],
    음식: [
      ['🍚', '밥', 'rice 밥'],
      ['🍜', '라면', 'ramen 국수'],
      ['🍕', '피자', 'pizza'],
      ['🍔', '햄버거', 'burger'],
      ['🍗', '치킨', 'chicken 닭'],
      ['🍣', '초밥', 'sushi'],
      ['🥟', '만두', 'dumpling'],
      ['🍺', '맥주', 'beer 술'],
      ['🍻', '건배', 'cheers 술 회식'],
      ['🍷', '와인', 'wine 술'],
      ['🍶', '전통주', 'sake 술 소주'],
      ['☕', '커피', 'coffee 카페'],
      ['🍰', '케이크', 'cake 디저트'],
      ['🍫', '초콜릿', 'chocolate'],
      ['🍎', '사과', 'apple'],
      ['🍉', '수박', 'watermelon 여름'],
      ['🍳', '계란', 'egg 요리']
    ],
    기호: [
      ['✅', '체크', 'check 완료 확인'],
      ['❌', '엑스', 'cross 실패 취소'],
      ['⚠️', '경고', 'warning 주의'],
      ['🚫', '금지', 'prohibited 안됨'],
      ['❗', '느낌표', 'exclamation 중요'],
      ['❓', '물음표', 'question 질문'],
      ['🔴', '빨강 원', 'red circle 정지'],
      ['🟢', '초록 원', 'green circle 정상'],
      ['🟡', '노랑 원', 'yellow circle 주의'],
      ['🔵', '파랑 원', 'blue circle'],
      ['➡️', '오른쪽', 'right arrow 화살표'],
      ['⬅️', '왼쪽', 'left arrow 화살표'],
      ['⬆️', '위', 'up arrow'],
      ['⬇️', '아래', 'down arrow'],
      ['🔄', '새로고침', 'refresh 반복 갱신'],
      ['♻️', '재활용', 'recycle 순환'],
      ['🆕', 'NEW', 'new 새로움'],
      ['🆗', 'OK', 'ok'],
      ['🔞', '19금', '18 성인'],
      ['🚧', '공사중', 'construction 작업중'],
      ['🐛', '벌레', 'bug 버그'],
      ['🚀', '로켓', 'rocket 배포 출시'],
      ['📈', '상승 그래프', 'chart up 성장'],
      ['📉', '하락 그래프', 'chart down 감소'],
      ['🏆', '트로피', 'trophy 우승'],
      ['🎯', '과녁', 'target 목표 정확']
    ]
  };

  window.RefTable?.define('emoji', {
    items: Object.keys(E).flatMap((group) =>
      E[group].map(([glyph, label, keywords]) => ({
        copy: glyph,
        glyph,
        label,
        keywords: `${label} ${keywords}`,
        group
      }))
    ),
    placeholder: '한국어로 찾기 (예: 웃음, 따봉, 배포, 버그)',
    copyNoun: '이모지',
    layout: 'grid',
    note: '누르면 이모지가 복사됩니다.'
  });

  Toolbox.register({
    id: 'emoji',
    title: '이모지 찾기',
    category: 'ref',
    desc: '한국어로 검색해서 이모지를 찾고 눌러서 복사합니다. 표정·손짓·기호 등 분류별',
    layout: 'wide',
    icon: '<circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.6" fill="none"/><circle cx="9" cy="10" r="1.2" fill="currentColor"/><circle cx="15" cy="10" r="1.2" fill="currentColor"/><path d="M8.5 14.5a4.5 4.5 0 0 0 7 0" stroke="currentColor" stroke-width="1.6" fill="none" stroke-linecap="round"/>',
    tabs: [
      {
        id: 'app',
        label: '이모지',
        build: function (container: HTMLElement): void {
          Mdd.linePreset('tool_run', { msg: '한국어로 찾아도 나와요.' });
          window.RefTable?.build(container, window.RefTable.get('emoji')!);
        }
      }
    ]
  });
})();
