const atelierSkins=[
 [{name:'잠 많은 마녀',src:'/.local/arcade-art/yawn-lobby-v1.png'},{name:'비 오는 귀갓길',src:'/.local/arcade-art/yawn-rainwalk-v1.png'},{name:'느긋한 휴일',src:'/.local/arcade-art/yawn-dayoff-v1.png'}],
 [{name:'저택의 메이드',src:'/.local/arcade-art/alisa-lobby-v2.png'},{name:'퇴근 후의 산책',src:'/.local/arcade-art/alisa-rainwalk-v1.png'},{name:'서가의 오후',src:'/.local/arcade-art/alisa-dayoff-v1.png'}],
 [{name:'장난꾸러기 강시',src:'/.local/arcade-art/ling-lobby-v1.png'},{name:'밤시장 나들이',src:'/.local/arcade-art/ling-rainwalk-v1.png'},{name:'오락실 단골',src:'/.local/arcade-art/ling-dayoff-v1.png'}],
 [{name:'소녀 연구소장',src:'/.local/arcade-art/timeto-lobby-v1.png'},{name:'별을 기록하는 밤',src:'/.local/arcade-art/timeto-rainwalk-v1.png'},{name:'실험 없는 일요일',src:'/.local/arcade-art/timeto-dayoff-v1.png'}]
];
let artCharacter=0,artOutfit=[0,0,0,0],atelierView='lobby',gameFilter='all';
const epithets=['잠이 덜 깬 밤의 마녀','빈틈을 허락하지 않는 메이드','한 판 더를 부르는 장난','작은 발견을 모으는 연구소장'];
const greetings=['...한 판만. 잠은 조금 뒤에 잘래.','자리는 정리해 두었습니다. 시작하시겠습니까.','오늘은 제가 먼저 이겨도 되죠~?','이번에는 어떤 결과가 나올까?'];
const covers=['gomoku','yacht','solitaire','reversi','four','checkers','blackjack','snake','pong','airhockey'];
function artSource(i=artCharacter){return atelierSkins[i][artOutfit[i]].src}
function star(){return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M32 3l5 22 22 7-22 5-5 24-5-24-24-5 24-7z" fill="currentColor"/><circle cx="32" cy="32" r="22" fill="none" stroke="currentColor" stroke-width=".5"/></svg>'}
function medallion(i){const paths=['M17 44q0-11 15-11t15 11 M32 31a10 10 0 1 0 0-20 10 10 0 0 0 0 20','M18 10h28v43H18z M22 14h20v35H22 M32 18v26 M23 31h18 M26 23l12 16 M38 23L26 39','M11 15q12-3 21 4 9-7 21-4v34q-12-3-21 4-9-7-21-4z M32 19v34 M16 23l10 2 M38 25l10-2 M16 30l10 2 M38 32l10-2','M9 18h46v31H9z M9 18l23 19 23-19 M9 49l17-15 M55 49L38 34','M12 11h40v43H12z M16 15h32v35H16z M32 15v35 M16 32h32 M19 41l7-7 9 9 7-5'][i];return `<span class="medal"><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="30"/><circle cx="32" cy="32" r="27"/><path d="${paths}"/></svg></span>`}
function rail(){return `<nav class="cast-rail" aria-label="캐릭터 디자인 선택">${names.map((n,i)=>`<button class="rail-portrait ${i===artCharacter?'selected':''}" onclick="chooseArt(${i})" aria-label="${n} 디자인 보기" aria-pressed="${i===artCharacter}"><img src="${atelierSkins[i][0].src}" alt=""><span>${n}</span></button>`).join('')}</nav>`}
function chooseArt(i){artCharacter=i;show(atelierView==='wardrobe'?'wardrobe':'lobby')}
function atelierLobby(){return `<section class="salon"><div class="salon-vignette"></div>${rail()}<img class="salon-art" src="${artSource()}" alt="${names[artCharacter]} / ${atelierSkins[artCharacter][artOutfit[artCharacter]].name}"><div class="salon-copy"><div class="brand-star">${star()}</div><span class="brand-overline">KARMOLAB / AFTER HOURS</span><h1>NIGHT ARCADE</h1><p class="brand-sub">밤이 머무는 오락실</p><button class="admission" onclick="show('games')"><span class="ticket-top">ADMIT ONE / 언제든 편하게</span><span class="ticket-title">게임 시작 <span>↗</span></span><span class="ticket-bottom">열 가지 놀이, 나의 속도로</span><span class="ticket-stamp">${star()}<small>PLAY<br>ALL NIGHT</small></span></button><button class="last-ticket" onclick="${s.played?"show('room')":"show('games')"}"><span>${s.played?'LAST PLAYED':'PICK YOUR GAME'}</span><b>${s.played?games[s.game]:'오늘은 어떤 게임?'}</b><i>→</i></button></div><div class="salon-dialogue"><small>${epithets[artCharacter]}</small><h2>${names[artCharacter]} <span>✧</span></h2><p>${greetings[artCharacter]}</p><button onclick="show('wardrobe')">옷장 열기　→</button></div><nav class="salon-dock">${['캐릭터','기원','기록','보관함','배경'].map((n,i)=>`<button onclick="show('${['wardrobe','gacha','profile','gift','background'][i]}')">${medallion(i)}<strong>${n}</strong><small>${['CHARACTERS','WISHES','RECORDS','LETTERS','SCENERY'][i]}</small></button>`).join('')}</nav><span class="skin-caption">DESIGN PREVIEW / ${atelierSkins[artCharacter][artOutfit[artCharacter]].name}</span></section>`}
function wardrobe(){return `<section class="wardrobe"><div class="wardrobe-title"><span class="brand-overline">THE PEOPLE OF OUR NIGHTS</span><h1>함께한 사람들</h1><button onclick="show('lobby')">← 로비로</button></div>${rail()}<div class="dress-portrait"><img src="${artSource()}" alt="${names[artCharacter]} ${atelierSkins[artCharacter][artOutfit[artCharacter]].name}"><button onclick="largeSkin()">일러스트 크게 보기　⤢</button></div><div class="dress-info"><span class="brand-overline">${['YAWN','ALISA','LING','TIMETO'][artCharacter]} / ${s.owned.includes(artCharacter)?'OWNED':'DESIGN PREVIEW'}</span><h2>${names[artCharacter]}</h2><p>${epithets[artCharacter]}</p><div class="bond-strip"><span>인연</span><b>${s.bond[artCharacter]}</b><div><i style="width:${Math.min(100,s.bond[artCharacter]*2)}%"></i></div><small>${s.owned.includes(artCharacter)?'함께한 시간':'미보유여도 함께한 시간은 남아요'}</small></div><div class="wardrobe-tabs"><strong>의상</strong><span>기본 + 스킨 2종</span></div><div class="skin-choices">${atelierSkins[artCharacter].map((k,j)=>`<button class="${j===artOutfit[artCharacter]?'active':''}" onclick="artOutfit[artCharacter]=${j};show('wardrobe')" aria-pressed="${j===artOutfit[artCharacter]}"><img src="${k.src}" alt="${k.name}"><small>${j===0?'ORIGINAL':'COSTUME 0'+j}</small><b>${k.name}</b></button>`).join('')}</div><div class="dress-actions"><button class="accent" onclick="show('lobby')">이 모습으로 로비 미리보기</button><button ${artCharacter!==2||!s.owned.includes(2)||s.bond[2]<50?'disabled':''} onclick="show('story')">인연 이야기 →</button></div><small class="wardrobe-note">모든 의상은 디자인 검토용으로 미리볼 수 있어요. 획득 조건과 가격은 미정입니다.</small></div></section>`}
function largeSkin(){const d=document.createElement('dialog');d.className='art-lightbox';d.innerHTML=`<img src="${artSource()}" alt="${names[artCharacter]} 스킨 초안"><button onclick="this.closest('dialog').close()">닫기 ×</button>`;d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal()}
function gamePage(){return page('오늘의 놀이',`<div class="catalog-head"><p>혼자서도, 함께여도. 마음 가는 한 판.</p><div class="catalog-tabs">${[['all','전체'],['board','보드와 카드'],['action','짧은 한 판']].map(([id,n])=>`<button class="${gameFilter===id?'active':''}" onclick="gameFilter='${id}';show('games')">${n}</button>`).join('')}</div></div><div class="game-posters">${games.map((g,i)=>({g,i})).filter(({i})=>gameFilter==='all'||(gameFilter==='action'?[7,8,9].includes(i):i<7)).map(({g,i})=>`<button onclick="s.game=${i};show('room')"><div class="poster-art"><img src="cover-${covers[i]}.svg" alt=""><span>${String(i+1).padStart(2,'0')}</span></div><div class="poster-label"><small>${i===2||i===7?'SOLO':'SOLO / TOGETHER'}</small><h2>${g}</h2><b>↗</b></div></button>`).join('')}</div>`)}
