const backgrounds=[{id:'rain',name:'비 오는 심야 라운지',src:'/.local/arcade-art/lobby-rain-v1.png'},{id:'neon',name:'네온 골목의 오락실',src:'/.local/arcade-art/v7-background.png'}];
let backdrop={id:'rain',blur:1,custom:null},draft;
try{const saved=JSON.parse(localStorage.getItem('arcade-lobby-design-v2'));if(saved&&['rain','neon','custom'].includes(saved.id)){backdrop={id:saved.id,blur:Math.min(6,Math.max(0,Number(saved.blur)||0)),custom:typeof saved.custom==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(saved.custom)?saved.custom:null}}}catch{}
function paintBackground(config){const src=config.id==='custom'&&config.custom?config.custom:(backgrounds.find(b=>b.id===config.id)||backgrounds[0]).src;document.documentElement.style.setProperty('--scene',`url("${src}")`);document.documentElement.style.setProperty('--blur',config.blur+'px')}
const iconPaths=['M6 5h12v14H6z M9 2v6 M15 2v6 M9 12h6 M9 16h4','M12 2l3 6 7 4-7 3-3 7-3-7-7-3 7-4z','M5 20V10h4v10 M10 20V4h4v16 M15 20v-7h4v7','M3 8h18v12H3z M2 5h20v4H2z M12 5v15','M3 4h18v16H3z M3 16l6-6 4 4 3-3 5 5 M15 8h.1'];
function decorate(){const portrait=document.querySelector('.portrait');if(portrait){portrait.src=s.equipped===0?'/.local/arcade-art/yawn-lobby-v1.png':'/.local/arcade-art/v7-character.png';portrait.alt=s.equipped===0?'욘 캐릭터 일러스트 초안':'다른 캐릭터의 임시 배치 일러스트';document.querySelector('.artnote').textContent=s.equipped===0?'YAWN / 캐릭터 디자인 초안':'일러스트 교체 예정';const h=document.querySelector('.hero');h.insertAdjacentHTML('afterbegin','<div class="lobby-title">밤은 아직<br>길잖아.<small>A LITTLE PLAY, A LITTLE COMPANY</small></div>');document.querySelector('.start strong').textContent='게임 시작';const dock=document.querySelector('.dock');dock.insertAdjacentHTML('beforeend','<button onclick="show(\'background\')"><b>배경</b>나의 공간</button>');dock.querySelectorAll('button').forEach((b,i)=>b.insertAdjacentHTML('afterbegin',`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[i]}"/></svg>`))}}
function renderBackground(){stats();$('screen').innerHTML=page('나의 공간',`<div class="bg-controls"><p class="muted">오늘의 캐릭터에게 어울리는 풍경을 골라보세요.</p><div class="bg-grid">${backgrounds.map(b=>`<button class="bg-choice ${draft.id===b.id?'active':''}" onclick="chooseBackground('${b.id}')"><img src="${b.src}" alt="${b.name}"><span>${b.name} ${draft.id===b.id?' / 선택됨':''}</span></button>`).join('')}</div><article class="panel"><label for="custom-bg">내 이미지 가져오기</label><input type="file" id="custom-bg" accept="image/png,image/jpeg,image/webp" onchange="uploadBackground(this)"><small>PNG, JPG, WebP / 3MB 이하. 이 브라우저에만 저장됩니다.</small>${draft.custom?`<button class="wide" onclick="chooseBackground('custom')">내 이미지 ${draft.id==='custom'?'선택됨':'선택'}</button>`:''}<label for="bg-blur">배경 흐림 <output id="blur-value">${draft.blur}</output></label><input type="range" id="bg-blur" min="0" max="6" step="1" value="${draft.blur}" oninput="draft.blur=Number(this.value);document.getElementById('blur-value').textContent=this.value;paintBackground(draft)"><p id="bg-status" class="settings-note">설정 저장을 누르면 로비에 적용됩니다. 캐릭터에는 흐림이 적용되지 않아요.</p><div class="bg-save"><button onclick="show('lobby')">취소</button><button class="accent" onclick="saveBackground()">설정 저장</button></div></article></div>`);paintBackground(draft)}
function chooseBackground(id){draft.id=id;renderBackground()}
function uploadBackground(input){const file=input.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>3*1024*1024){$('bg-status').textContent='3MB 이하의 PNG, JPG, WebP를 선택해 주세요.';return}const reader=new FileReader();reader.onload=()=>{draft.custom=String(reader.result);draft.id='custom';renderBackground()};reader.onerror=()=>{$('bg-status').textContent='이미지를 읽지 못했어요. 다른 파일을 선택해 주세요.'};reader.readAsDataURL(file)}
function saveBackground(){try{localStorage.setItem('arcade-lobby-design-v2',JSON.stringify(draft));backdrop={...draft};show('lobby')}catch{$('bg-status').textContent='브라우저 저장 공간이 부족해요. 더 작은 이미지를 선택해 주세요.'}}
const castArt=['/.local/arcade-art/yawn-lobby-v1.png','/.local/arcade-art/alisa-lobby-v1.png','/.local/arcade-art/ling-lobby-v1.png','/.local/arcade-art/timeto-lobby-v1.png'];
const priorDecorate=decorate;
decorate=function(){priorDecorate();const portrait=document.querySelector('.portrait');if(portrait){portrait.src=castArt[s.equipped];portrait.alt=names[s.equipped]+' 일러스트 초안';document.querySelector('.artnote').textContent=names[s.equipped]+' / 캐릭터 디자인 초안'}document.querySelectorAll('.castgrid .sigil').forEach((el,i)=>{el.textContent='';el.style.background=`url('${castArt[i]}') center 18% / cover`;el.style.height=el.closest('.castcard')?'230px':'100px';el.setAttribute('role','img');el.setAttribute('aria-label',names[i]+' 일러스트');if(el.closest('.castcard')){const b=document.createElement('button');b.className='wide';b.textContent='일러스트 크게 보기';b.onclick=()=>previewArt(i);el.after(b)}})};
function previewArt(i){const d=document.createElement('dialog');d.style.maxWidth='620px';d.style.padding='16px';const image=document.createElement('img');image.src=castArt[i];image.alt=names[i]+' 일러스트 초안';image.style.cssText='display:block;max-height:72svh;max-width:100%;margin:auto';const h=document.createElement('h2');h.textContent=names[i]+' / 초안';const b=document.createElement('button');b.textContent='닫기';b.onclick=()=>d.close();d.append(h,image,b);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal()}
