/** 흥 화면 뼈대. 값이 안 들어가는 고정 마크업 (TASK-KL-220). 동작은 없다. */
export const HEUNG_SHELL = `<div class="hu-root">
      <div class="hu-toolbar">
        <span class="hu-brand">흥</span><button class="btn btn-tool" data-act="new">새 곡</button><button class="btn btn-tool" data-act="open">프로젝트 열기</button><button class="btn btn-tool" data-act="save" title="다른 기기에서도 열 수 있는 프로젝트 파일을 받습니다">프로젝트 받기</button><button class="btn btn-tool" data-act="undo" title="실행 취소 (Ctrl+Z)">↶</button><button class="btn btn-tool" data-act="redo" title="다시 실행 (Ctrl+Y)">↷</button>
        <input class="hu-project-name" data-bind="project-name" aria-label="프로젝트 이름">
        <button class="btn btn-tool" data-act="back" aria-label="처음으로">|◀</button><button class="btn btn-tool" data-act="play" aria-label="재생">▶</button><button class="btn btn-tool" data-act="stop" aria-label="정지">■</button><button class="btn btn-tool" data-act="record" aria-label="마이크 녹음">● REC</button><button class="btn btn-tool" data-act="metronome" title="박자 소리 (마디 첫 박은 높게)">🎵 CLICK</button><button class="btn btn-tool" data-act="count-in" title="녹음 전에 한 마디 세어 준다">COUNT-IN</button>
        <span class="hu-time" data-role="time">1.1.00</span><label>BPM <input class="hu-number" data-bind="bpm" type="number" min="30" max="300"></label><label>METER <select class="hu-number" data-bind="meter"><option value="3">3/4</option><option value="4">4/4</option><option value="5">5/4</option><option value="6">6/4</option><option value="7">7/4</option></select></label>
        <label>SWING <select class="hu-number" data-bind="swing"><option value="0">0</option><option value="0.15">15%</option><option value="0.3">30%</option><option value="0.45">45%</option><option value="0.6">60%</option></select></label><label>SNAP <select class="hu-number" data-bind="snap"><option value="1">1</option><option value="0.5">1/2</option><option value="0.25">1/4</option><option value="0.125">1/8</option><option value="0.0625">1/16</option><option value="0.3333333333333333">1/4 셋잇단</option><option value="0.16666666666666666">1/8 셋잇단</option><option value="0.08333333333333333">1/16 셋잇단</option><option value="0.375">1/4 점음표</option><option value="0.1875">1/8 점음표</option></select></label>
        <button class="btn btn-tool is-on" data-tool="draw" title="그리기 (P)">✎ DRAW</button><button class="btn btn-tool" data-tool="select" title="선택 (E)">□ SELECT</button><button class="btn btn-tool" data-tool="slice" title="자르기 (C)">╱ SLICE</button>
        <button class="btn btn-tool" data-act="loop">구간 반복</button><button class="btn btn-tool" data-act="tap" title="박자에 맞춰 여러 번 눌러 빠르기를 정합니다">박자 두드리기</button><button class="btn btn-tool" data-act="play-selection" title="고른 클립 구간만 반복 재생 (Shift+Space)">▶ 고른 구간 반복</button><button class="btn btn-tool" data-act="audio">+ 오디오 트랙</button><button class="btn btn-tool" data-act="midi">+ 악기 트랙</button><button class="btn btn-tool" data-act="import-audio">음원 가져오기</button><button class="btn btn-tool" data-act="import-midi">MIDI 가져오기</button><button class="btn btn-tool" data-act="export-midi">MIDI 내보내기</button>
        <button class="btn btn-tool" data-act="cut" title="잘라내기 (Ctrl+X)">CUT</button><button class="btn btn-tool" data-act="copy" title="복사 (Ctrl+C)">COPY</button><button class="btn btn-tool" data-act="paste" title="붙여넣기 (Ctrl+V)">PASTE</button>
        <span class="hu-spacer"></span><button class="btn btn-tool" data-act="zoom-out">−</button><button class="btn btn-tool" data-act="zoom-in">＋</button><button class="btn btn-tool" data-act="export-wav">WAV로 완성하기</button><button class="btn btn-tool" data-act="help" title="단축키 (?)">?</button><button class="btn btn-tool" data-act="restore-prev" title="새 곡이나 프로젝트 열기 직전의 곡으로 되돌립니다" hidden>직전 곡 되찾기</button><span class="hu-status" data-role="status" role="status" aria-live="polite">준비됨, 자동 저장 켜짐</span>
      </div>
      <div class="hu-guide" data-role="guide" hidden><b>첫 소리까지 3단계</b><span>1. <em>First idea</em>를 더블클릭</span><span>2. 왼쪽 건반으로 듣고 빈칸에 음 찍기</span><span>3. <em>▶</em>로 듣고 <em>WAV로 완성하기</em></span><small>샘플은 연습용이며 언제든 지워도 됩니다. 작업은 이 브라우저에 자동 저장됩니다.</small><span class="hu-spacer"></span><button class="btn btn-tool" data-act="guide-close" title="다시 안 보기">시작하기</button></div><div class="hu-work"><div class="hu-arranger"><div class="hu-scroll" data-role="scroll"><div class="hu-ruler" data-role="ruler"></div><div data-role="tracks"></div><div class="hu-playhead" data-role="playhead"></div><div class="hu-band" data-role="band" hidden></div></div><div class="hu-editor" data-role="editor"></div></div>
      <aside class="hu-side"><div class="hu-side-tabs"><button class="btn btn-tool is-on" data-side="inspector">INSPECTOR</button><button class="btn btn-tool" data-side="mixer">MIXER</button></div><div class="hu-side-body" data-role="side"></div></aside></div>
      <div class="hu-modal-backdrop" data-role="backdrop"></div><div data-role="export"></div><div data-role="help"></div><div class="hu-context" data-role="context" role="menu" hidden></div>
      <input type="file" data-file="audio" accept="audio/*" multiple hidden><input type="file" data-file="midi" accept="audio/midi,audio/x-midi,.mid,.midi" hidden><input type="file" data-file="project" accept="application/json,.json" hidden>
    </div>`;
