import { t } from '../../lib/i18n';
import { rng } from './rules';
import { Boids, BoidWatcher, type BoidStats } from './boids';
import { createObservationControls } from './observation-controls';

export function buildBoids(container: HTMLElement): void {
  if (!document.getElementById('bd-style')) { const style = document.createElement('style'); style.id = 'bd-style'; style.textContent = `.bd-wrap{position:relative;width:100%;height:clamp(420px,78svh,900px);overflow:hidden;border-radius:var(--radius-md,12px);background:#07111b}.bd-canvas{display:block;width:100%;height:100%}.bd-head{position:absolute;inset:0 0 auto;display:flex;gap:9px;align-items:baseline;padding:13px 15px 30px;pointer-events:none;background:linear-gradient(#07111be8,transparent)}.bd-name{color:#e8f8ff;font-size:13px}.bd-code,.bd-step{color:#b8d3df80;font:11px var(--font-mono,monospace)}.bd-step{margin-left:auto}.bd-actions{position:absolute;right:12px;top:45px;display:flex;gap:6px}.bd-btn{border:1px solid #ffffff28;background:#0b1b29bd;color:#dff6ff;padding:6px 9px;border-radius:999px;cursor:pointer;font:11px var(--font-mono,monospace)}.bd-btn[aria-pressed="true"]{border-color:#72cbef88;background:#164661bd}.bd-log{position:absolute;inset:auto 0 0;padding:35px 16px 16px;color:#e8f9ff;font-size:14px;line-height:1.45;pointer-events:none;background:linear-gradient(transparent,#07111be8)}.bd-hint{display:block;margin-top:3px;color:#b8d3df80;font:11px var(--font-mono,monospace)}`; document.head.appendChild(style); }
  const wrap = document.createElement('div'); wrap.className = 'bd-wrap'; const canvas = document.createElement('canvas'); canvas.className = 'bd-canvas'; const head = document.createElement('div'); head.className = 'bd-head'; const name = document.createElement('span'); name.className = 'bd-name'; const code = document.createElement('span'); code.className = 'bd-code'; const stepEl = document.createElement('span'); stepEl.className = 'bd-step'; head.append(name, code, stepEl); const actions = document.createElement('div'); actions.className = 'bd-actions'; const reseed = document.createElement('button'); reseed.type = 'button'; reseed.className = 'bd-btn'; const pause = document.createElement('button'); pause.type = 'button'; pause.className = 'bd-btn'; actions.append(reseed, pause); const log = document.createElement('div'); log.className = 'bd-log'; const line = document.createElement('span'); const hint = document.createElement('span'); hint.className = 'bd-hint'; log.append(line, hint); wrap.append(canvas, head, actions, log); container.appendChild(wrap);
  const ctx = canvas.getContext('2d'); if (!ctx) return; const c = ctx; const day = new Date().toISOString().slice(0, 10); let seedNo = 0, paused = false; let raf: number | undefined; const sim = new Boids(190, 2); const watcher = new BoidWatcher();
  function randomFor(extra: number): () => number { let hash = extra * 2654435761; for (let i = 0; i < day.length; i++) hash = Math.imul(hash ^ day.charCodeAt(i), 16777619); return rng(hash >>> 0); }
  function resize(): void { const r = wrap.getBoundingClientRect(); const dpr = Math.min(2, devicePixelRatio || 1); canvas.width = Math.max(1, Math.round(r.width * dpr)); canvas.height = Math.max(1, Math.round((r.height || 420) * dpr)); }
  function plant(): void { seedNo++; sim.seed(randomFor(seedNo)); watcher.reset(); line.textContent = t('garden.bd.seeded', { n: seedNo }); }
  function triangle(x: number, y: number, vx: number, vy: number, size: number, color: string): void { const a = Math.atan2(vy, vx); c.save(); c.translate(x, y); c.rotate(a); c.fillStyle = color; c.beginPath(); c.moveTo(size, 0); c.lineTo(-size * 0.72, size * 0.5); c.lineTo(-size * 0.45, 0); c.lineTo(-size * 0.72, -size * 0.5); c.closePath(); c.fill(); c.restore(); }
  function draw(stats: BoidStats): void { const w = canvas.width, h = canvas.height; c.fillStyle = 'rgba(7,17,27,.34)'; c.fillRect(0, 0, w, h); for (let i = 0; i < sim.count; i++) triangle(sim.x[i] * w, sim.y[i] * h, sim.vx[i], sim.vy[i], 4.2, '#b9ecff'); for (let p = 0; p < sim.predatorCount; p++) triangle(sim.px[p] * w, sim.py[p] * h, sim.pvx[p], sim.pvy[p], 9, '#ff7b69'); stepEl.textContent = t('garden.bd.step', { n: stats.step, f: stats.flocks }); }
  const controls = createObservationControls();
  container.querySelector('.bd-actions')?.appendChild(controls.element);
  function frame(): void { raf = requestAnimationFrame(frame); if (paused) return; let stats = null as unknown as BoidStats; controls.run(1, () => { stats = sim.step(); }); const event = watcher.observe(stats); if (event) line.textContent = t(`garden.bd.event.${event}`, { n: stats.step, f: stats.flocks }); draw(stats); if (stats.step >= 8000) plant(); }
  reseed.onclick = plant; pause.onclick = () => { paused = !paused; pause.setAttribute('aria-pressed', String(paused)); pause.textContent = t(paused ? 'garden.resume' : 'garden.pause'); }; reseed.textContent = t('garden.reseed'); pause.textContent = t('garden.pause'); name.textContent = t('garden.bd.name'); code.textContent = t('garden.bd.code'); hint.textContent = t('garden.bd.hint'); resize(); plant(); line.textContent = t('garden.bd.today'); raf = requestAnimationFrame(frame); const ro = new ResizeObserver(resize); ro.observe(wrap); Toolbox.onDispose?.(() => { if (raf !== undefined) cancelAnimationFrame(raf); ro.disconnect(); });
}
