import { t } from '../../lib/i18n';
import { rng } from './rules';
import { EvolutionWatcher, GeneticEvolution, type EvolutionStats } from './genetic-evolution';
import { createObservationControls } from './observation-controls';

const COLORS = ['#77d9ff','#ffd36f','#ff7f9e','#a990ff','#76e39b','#ff9f63','#72d8ca','#e792dd'];

export function buildGeneticEvolution(container: HTMLElement): void {
  if (!document.getElementById('ev-style')) { const style = document.createElement('style'); style.id = 'ev-style'; style.textContent = `.ev-wrap{position:relative;width:100%;height:clamp(420px,78svh,900px);overflow:hidden;border-radius:var(--radius-md,12px);background:#080b10}.ev-canvas{display:block;width:100%;height:100%}.ev-head{position:absolute;inset:0 0 auto;display:flex;gap:9px;align-items:baseline;padding:13px 15px 30px;pointer-events:none;background:linear-gradient(#080b10e8,transparent)}.ev-name{color:#f1f7ff;font-size:13px}.ev-code,.ev-step{color:#c2ccdc80;font:11px var(--font-mono,monospace)}.ev-step{margin-left:auto}.ev-actions{position:absolute;right:12px;top:45px;display:flex;gap:6px}.ev-btn{border:1px solid #ffffff28;background:#121925bd;color:#edf4ff;padding:6px 9px;border-radius:999px;cursor:pointer;font:11px var(--font-mono,monospace)}.ev-btn[aria-pressed="true"]{border-color:#7fb4ff88;background:#243b61bd}.ev-log{position:absolute;inset:auto 0 0;padding:35px 16px 16px;color:#edf5ff;font-size:14px;line-height:1.45;pointer-events:none;background:linear-gradient(transparent,#080b10e8)}.ev-hint{display:block;margin-top:3px;color:#c2ccdc80;font:11px var(--font-mono,monospace)}`; document.head.appendChild(style); }
  const wrap = document.createElement('div'); wrap.className = 'ev-wrap'; const canvas = document.createElement('canvas'); canvas.className = 'ev-canvas'; const head = document.createElement('div'); head.className = 'ev-head'; const name = document.createElement('span'); name.className = 'ev-name'; const code = document.createElement('span'); code.className = 'ev-code'; const stepEl = document.createElement('span'); stepEl.className = 'ev-step'; head.append(name, code, stepEl); const actions = document.createElement('div'); actions.className = 'ev-actions'; const reseed = document.createElement('button'); reseed.type = 'button'; reseed.className = 'ev-btn'; const pause = document.createElement('button'); pause.type = 'button'; pause.className = 'ev-btn'; actions.append(reseed, pause); const log = document.createElement('div'); log.className = 'ev-log'; const line = document.createElement('span'); const hint = document.createElement('span'); hint.className = 'ev-hint'; log.append(line, hint); wrap.append(canvas, head, actions, log); container.appendChild(wrap);
  const ctx = canvas.getContext('2d'); if (!ctx) return; const c = ctx; const day = new Date().toISOString().slice(0, 10); let seedNo = 0, paused = false; let raf: number | undefined; const sim = new GeneticEvolution(); let random = rng(1); const watcher = new EvolutionWatcher();
  function randomFor(extra: number): () => number { let hash = extra * 2654435761; for (let i = 0; i < day.length; i++) hash = Math.imul(hash ^ day.charCodeAt(i), 16777619); return rng(hash >>> 0); }
  function resize(): void { const r = wrap.getBoundingClientRect(); const dpr = Math.min(2, devicePixelRatio || 1); canvas.width = Math.max(1, Math.round(r.width * dpr)); canvas.height = Math.max(1, Math.round((r.height || 420) * dpr)); }
  function plant(): void { seedNo++; random = randomFor(seedNo); sim.seed(random); watcher.reset(); line.textContent = t('garden.ev.seeded', { n: seedNo }); }
  function draw(stats: EvolutionStats): void { const w = canvas.width, h = canvas.height; c.fillStyle = 'rgba(8,11,16,.25)'; c.fillRect(0, 0, w, h); c.fillStyle = '#d8f29a'; for (let f = 0; f < sim.foodCount; f++) { c.beginPath(); c.arc(sim.foodX[f] * w, sim.foodY[f] * h, 2.6, 0, Math.PI * 2); c.fill(); } for (let i = 0; i < sim.count; i++) { const color = COLORS[sim.speciesOf[i] % COLORS.length]; const a = sim.heading[i], size = 3.3 + sim.energy[i] * 1.8; c.save(); c.translate(sim.x[i] * w, sim.y[i] * h); c.rotate(a); c.fillStyle = color; c.beginPath(); c.moveTo(size, 0); c.lineTo(-size, size * 0.56); c.lineTo(-size * 0.5, 0); c.lineTo(-size, -size * 0.56); c.closePath(); c.fill(); c.restore(); } stepEl.textContent = t('garden.ev.step', { g: stats.generation, n: stats.tick, s: stats.species }); }
  const controls = createObservationControls();
  container.querySelector('.ev-actions')?.appendChild(controls.element);
  function frame(): void { raf = requestAnimationFrame(frame); if (paused) return; let stats = null as unknown as EvolutionStats; controls.run(2, () => { stats = sim.step(random); }); const event = watcher.observe(stats); if (event) line.textContent = t(`garden.ev.event.${event}`, { g: stats.generation, best: Math.round(stats.bestFitness), d: stats.diversity.toFixed(2), s: stats.species, id: stats.champion }); draw(stats); }
  reseed.onclick = plant; pause.onclick = () => { paused = !paused; pause.setAttribute('aria-pressed', String(paused)); pause.textContent = t(paused ? 'garden.resume' : 'garden.pause'); }; reseed.textContent = t('garden.reseed'); pause.textContent = t('garden.pause'); name.textContent = t('garden.ev.name'); code.textContent = t('garden.ev.code'); hint.textContent = t('garden.ev.hint'); resize(); plant(); line.textContent = t('garden.ev.today'); raf = requestAnimationFrame(frame); const ro = new ResizeObserver(resize); ro.observe(wrap); Toolbox.onDispose?.(() => { if (raf !== undefined) cancelAnimationFrame(raf); ro.disconnect(); });
}
