import { t } from '../../lib/i18n';
import { rng } from './rules';
import { Lenia, LeniaWatcher, leniaPresetForDay, type LeniaStats } from './lenia';

export function buildLenia(container: HTMLElement): void {
  if (!document.getElementById('ln-style')) { const style = document.createElement('style'); style.id = 'ln-style'; style.textContent = `.ln-wrap{position:relative;width:100%;height:clamp(420px,78svh,900px);overflow:hidden;border-radius:var(--radius-md,12px);background:#05080b}.ln-canvas{display:block;width:100%;height:100%;image-rendering:pixelated}.ln-head{position:absolute;inset:0 0 auto;display:flex;gap:9px;align-items:baseline;padding:13px 15px 30px;pointer-events:none;background:linear-gradient(#05080be8,transparent)}.ln-name{color:#e9fffb;font-size:13px}.ln-code,.ln-step{color:#b4ddd580;font:11px var(--font-mono,monospace)}.ln-step{margin-left:auto}.ln-actions{position:absolute;right:12px;top:45px;display:flex;gap:6px}.ln-btn{border:1px solid #ffffff28;background:#0b1b1abd;color:#dffbf6;padding:6px 9px;border-radius:999px;cursor:pointer;font:11px var(--font-mono,monospace)}.ln-btn[aria-pressed="true"]{border-color:#6ce2cf88;background:#155148bd}.ln-log{position:absolute;inset:auto 0 0;padding:35px 16px 16px;color:#e9fffb;font-size:14px;line-height:1.45;pointer-events:none;background:linear-gradient(transparent,#05080be8)}.ln-hint{display:block;margin-top:3px;color:#b4ddd580;font:11px var(--font-mono,monospace)}`; document.head.appendChild(style); }
  const wrap = document.createElement('div'); wrap.className = 'ln-wrap'; const canvas = document.createElement('canvas'); canvas.className = 'ln-canvas'; const head = document.createElement('div'); head.className = 'ln-head'; const name = document.createElement('span'); name.className = 'ln-name'; const code = document.createElement('span'); code.className = 'ln-code'; const stepEl = document.createElement('span'); stepEl.className = 'ln-step'; head.append(name, code, stepEl); const actions = document.createElement('div'); actions.className = 'ln-actions'; const reseed = document.createElement('button'); reseed.type = 'button'; reseed.className = 'ln-btn'; const pause = document.createElement('button'); pause.type = 'button'; pause.className = 'ln-btn'; actions.append(reseed, pause); const log = document.createElement('div'); log.className = 'ln-log'; const line = document.createElement('span'); const hint = document.createElement('span'); hint.className = 'ln-hint'; log.append(line, hint); wrap.append(canvas, head, actions, log); container.appendChild(wrap);
  const ctx = canvas.getContext('2d'); if (!ctx) return; const c = ctx; const field = document.createElement('canvas'); const fc = field.getContext('2d'); if (!fc) return; const day = new Date().toISOString().slice(0, 10); const preset = leniaPresetForDay(day); let seedNo = 0, paused = false; let raf: number | undefined; let sim = new Lenia(1, 1, preset); let pixels = fc.createImageData(1, 1); const watcher = new LeniaWatcher();
  function randomFor(extra: number): () => number { let hash = extra * 2654435761; for (let i = 0; i < day.length; i++) hash = Math.imul(hash ^ day.charCodeAt(i), 16777619); return rng(hash >>> 0); }
  function build(): void { const r = wrap.getBoundingClientRect(); const w = Math.max(72, Math.floor(r.width / 6)); const h = Math.max(48, Math.floor((r.height || 420) / 6)); canvas.width = Math.max(1, Math.round(r.width)); canvas.height = Math.max(1, Math.round(r.height || 420)); field.width = w; field.height = h; pixels = fc!.createImageData(w, h); sim = new Lenia(w, h, preset); plant(); }
  function plant(): void { seedNo++; sim.seed(randomFor(seedNo)); watcher.reset(); line.textContent = t('garden.ln.seeded', { n: seedNo }); }
  function draw(stats: LeniaStats): void { const data = pixels.data; for (let i = 0, p = 0; i < sim.cells.length; i++, p += 4) { const q = Math.max(0, Math.min(1, sim.cells[i])); data[p] = 5 + q * 96; data[p + 1] = 9 + q * 225; data[p + 2] = 12 + q * 190; data[p + 3] = 255; } fc!.putImageData(pixels, 0, 0); c.imageSmoothingEnabled = true; c.drawImage(field, 0, 0, canvas.width, canvas.height); stepEl.textContent = t('garden.ln.step', { n: stats.step }); }
  function frame(): void { raf = requestAnimationFrame(frame); if (paused) return; const stats = sim.step(); const event = watcher.observe(stats); if (event) line.textContent = t(`garden.ln.event.${event}`, { n: stats.step, c: stats.components }); draw(stats); if (stats.step >= 3200 || stats.mass < 0.00005) plant(); }
  reseed.onclick = plant; pause.onclick = () => { paused = !paused; pause.setAttribute('aria-pressed', String(paused)); pause.textContent = t(paused ? 'garden.resume' : 'garden.pause'); }; reseed.textContent = t('garden.reseed'); pause.textContent = t('garden.pause'); name.textContent = t(`garden.ln.preset.${preset.id}`); code.textContent = `R ${preset.radius} · μ ${preset.mu} · σ ${preset.sigma}`; hint.textContent = t('garden.ln.hint'); build(); line.textContent = t('garden.ln.today', { name: name.textContent }); raf = requestAnimationFrame(frame); const ro = new ResizeObserver(() => { const r = wrap.getBoundingClientRect(); const w = Math.max(72, Math.floor(r.width / 6)); const h = Math.max(48, Math.floor((r.height || 420) / 6)); if (w !== sim.w || h !== sim.h) build(); }); ro.observe(wrap); Toolbox.onDispose?.(() => { if (raf !== undefined) cancelAnimationFrame(raf); ro.disconnect(); });
}

