import { t } from '../../lib/i18n';
import { rng } from './rules';
import { NeuralCA, NeuralWatcher, neuralShapeForDay, type NeuralStats } from './neural-ca';

export function buildNeuralCA(container: HTMLElement): void {
  if (!document.getElementById('nc-style')) { const style = document.createElement('style'); style.id = 'nc-style'; style.textContent = `.nc-wrap{position:relative;width:100%;height:clamp(420px,78svh,900px);overflow:hidden;border-radius:var(--radius-md,12px);background:#08060d}.nc-canvas{display:block;width:100%;height:100%;image-rendering:pixelated}.nc-head{position:absolute;inset:0 0 auto;display:flex;gap:9px;align-items:baseline;padding:13px 15px 30px;pointer-events:none;background:linear-gradient(#08060de8,transparent)}.nc-name{color:#f7e9ff;font-size:13px}.nc-code,.nc-step{color:#d7bbe380;font:11px var(--font-mono,monospace)}.nc-step{margin-left:auto}.nc-actions{position:absolute;right:12px;top:45px;display:flex;gap:6px}.nc-btn{border:1px solid #ffffff28;background:#1b1024bd;color:#f5ddff;padding:6px 9px;border-radius:999px;cursor:pointer;font:11px var(--font-mono,monospace)}.nc-btn[aria-pressed="true"]{border-color:#d58bf088;background:#522664bd}.nc-log{position:absolute;inset:auto 0 0;padding:35px 16px 16px;color:#f8eaff;font-size:14px;line-height:1.45;pointer-events:none;background:linear-gradient(transparent,#08060de8)}.nc-hint{display:block;margin-top:3px;color:#d7bbe380;font:11px var(--font-mono,monospace)}`; document.head.appendChild(style); }
  const wrap = document.createElement('div'); wrap.className = 'nc-wrap'; const canvas = document.createElement('canvas'); canvas.className = 'nc-canvas'; const head = document.createElement('div'); head.className = 'nc-head'; const name = document.createElement('span'); name.className = 'nc-name'; const code = document.createElement('span'); code.className = 'nc-code'; const stepEl = document.createElement('span'); stepEl.className = 'nc-step'; head.append(name, code, stepEl); const actions = document.createElement('div'); actions.className = 'nc-actions'; const damage = document.createElement('button'); damage.type = 'button'; damage.className = 'nc-btn'; const reseed = document.createElement('button'); reseed.type = 'button'; reseed.className = 'nc-btn'; const pause = document.createElement('button'); pause.type = 'button'; pause.className = 'nc-btn'; actions.append(damage, reseed, pause); const log = document.createElement('div'); log.className = 'nc-log'; const line = document.createElement('span'); const hint = document.createElement('span'); hint.className = 'nc-hint'; log.append(line, hint); wrap.append(canvas, head, actions, log); container.appendChild(wrap);
  const ctx = canvas.getContext('2d'); if (!ctx) return; const c = ctx; const field = document.createElement('canvas'); const fc = field.getContext('2d'); if (!fc) return; const day = new Date().toISOString().slice(0, 10); const shape = neuralShapeForDay(day); let seedNo = 0, paused = false, autoDamaged = false; let raf: number | undefined; let sim = new NeuralCA(1, 1, shape); let pixels = fc.createImageData(1, 1); let random = rng(1); const watcher = new NeuralWatcher();
  function randomFor(extra: number): () => number { let hash = extra * 2654435761; for (let i = 0; i < day.length; i++) hash = Math.imul(hash ^ day.charCodeAt(i), 16777619); return rng(hash >>> 0); }
  function build(): void { const r = wrap.getBoundingClientRect(); const w = Math.max(72, Math.floor(r.width / 5)); const h = Math.max(48, Math.floor((r.height || 420) / 5)); canvas.width = Math.max(1, Math.round(r.width)); canvas.height = Math.max(1, Math.round(r.height || 420)); field.width = w; field.height = h; pixels = fc!.createImageData(w, h); sim = new NeuralCA(w, h, shape); plant(); }
  function plant(): void { seedNo++; random = randomFor(seedNo); sim.seed(); watcher.reset(); autoDamaged = false; line.textContent = t('garden.nc.seeded', { n: seedNo }); }
  function hurt(): void { sim.damage(random); autoDamaged = true; line.textContent = t(`garden.nc.event.${watcher.markDamage(sim.stepNo)}`, { n: sim.stepNo }); }
  function draw(stats: NeuralStats): void { const data = pixels.data; for (let i = 0, p = 0; i < sim.cells.length; i++, p += 4) { const q = sim.cells[i], ghost = sim.target[i] * 0.08; data[p] = 9 + ghost * 90 + q * 205; data[p + 1] = 6 + ghost * 42 + q * 105; data[p + 2] = 14 + ghost * 105 + q * 230; data[p + 3] = 255; } fc!.putImageData(pixels, 0, 0); c.imageSmoothingEnabled = true; c.drawImage(field, 0, 0, canvas.width, canvas.height); stepEl.textContent = t('garden.nc.step', { n: stats.step, p: Math.round(stats.similarity * 100) }); }
  function frame(): void { raf = requestAnimationFrame(frame); if (paused) return; let stats = sim.step(random); stats = sim.step(random); const event = watcher.observe(stats); if (event) line.textContent = t(`garden.nc.event.${event}`, { n: stats.step, p: Math.round(stats.similarity * 100) }); if (!autoDamaged && stats.step >= 700) hurt(); draw(stats); if (stats.step >= 2400) plant(); }
  damage.onclick = hurt; reseed.onclick = plant; pause.onclick = () => { paused = !paused; pause.setAttribute('aria-pressed', String(paused)); pause.textContent = t(paused ? 'garden.resume' : 'garden.pause'); }; damage.textContent = t('garden.nc.damage'); reseed.textContent = t('garden.reseed'); pause.textContent = t('garden.pause'); name.textContent = t(`garden.nc.shape.${shape}`); code.textContent = t('garden.nc.code'); hint.textContent = t('garden.nc.hint'); build(); line.textContent = t('garden.nc.today', { shape: name.textContent }); raf = requestAnimationFrame(frame); const ro = new ResizeObserver(() => { const r = wrap.getBoundingClientRect(); const w = Math.max(72, Math.floor(r.width / 5)); const h = Math.max(48, Math.floor((r.height || 420) / 5)); if (w !== sim.w || h !== sim.h) build(); }); ro.observe(wrap); Toolbox.onDispose?.(() => { if (raf !== undefined) cancelAnimationFrame(raf); ro.disconnect(); });
}

