import { t } from '../../lib/i18n';
import { rng } from './rules';
import { Material, SandTerrarium, TerrariumWatcher, type TerrariumStats } from './sand-terrarium';

const COLORS = [[6,8,11],[73,70,68],[111,76,48],[210,164,89],[54,132,203],[59,159,76],[255,111,38],[126,132,142]];

export function buildSandTerrarium(container: HTMLElement): void {
  if (!document.getElementById('st-style')) { const style = document.createElement('style'); style.id = 'st-style'; style.textContent = `.st-wrap{position:relative;width:100%;height:clamp(420px,78svh,900px);overflow:hidden;border-radius:var(--radius-md,12px);background:#06080b}.st-canvas{display:block;width:100%;height:100%;image-rendering:pixelated}.st-head{position:absolute;inset:0 0 auto;display:flex;gap:9px;align-items:baseline;padding:13px 15px 30px;pointer-events:none;background:linear-gradient(#06080be8,transparent)}.st-name{color:#fff2d2;font-size:13px}.st-code,.st-step{color:#d7c9aa80;font:11px var(--font-mono,monospace)}.st-step{margin-left:auto}.st-actions{position:absolute;right:12px;top:45px;display:flex;gap:6px}.st-btn{border:1px solid #ffffff28;background:#19140dbd;color:#ffedc7;padding:6px 9px;border-radius:999px;cursor:pointer;font:11px var(--font-mono,monospace)}.st-btn[aria-pressed="true"]{border-color:#f1c66a88;background:#4b3914bd}.st-log{position:absolute;inset:auto 0 0;padding:35px 16px 16px;color:#fff1d8;font-size:14px;line-height:1.45;pointer-events:none;background:linear-gradient(transparent,#06080be8)}.st-hint{display:block;margin-top:3px;color:#d7c9aa80;font:11px var(--font-mono,monospace)}`; document.head.appendChild(style); }
  const wrap = document.createElement('div'); wrap.className = 'st-wrap'; const canvas = document.createElement('canvas'); canvas.className = 'st-canvas'; const head = document.createElement('div'); head.className = 'st-head'; const name = document.createElement('span'); name.className = 'st-name'; const code = document.createElement('span'); code.className = 'st-code'; const stepEl = document.createElement('span'); stepEl.className = 'st-step'; head.append(name, code, stepEl); const actions = document.createElement('div'); actions.className = 'st-actions'; const reseed = document.createElement('button'); reseed.type = 'button'; reseed.className = 'st-btn'; const pause = document.createElement('button'); pause.type = 'button'; pause.className = 'st-btn'; actions.append(reseed, pause); const log = document.createElement('div'); log.className = 'st-log'; const line = document.createElement('span'); const hint = document.createElement('span'); hint.className = 'st-hint'; log.append(line, hint); wrap.append(canvas, head, actions, log); container.appendChild(wrap);
  const ctx = canvas.getContext('2d'); if (!ctx) return; const c = ctx; const field = document.createElement('canvas'); const fc = field.getContext('2d'); if (!fc) return;
  const day = new Date().toISOString().slice(0, 10); let seedNo = 0, paused = false; let raf: number | undefined; let sim = new SandTerrarium(1, 1); let pixels = fc.createImageData(1, 1); let random = rng(1); const watcher = new TerrariumWatcher();
  function randomFor(extra: number): () => number { let hash = extra * 2654435761; for (let i = 0; i < day.length; i++) hash = Math.imul(hash ^ day.charCodeAt(i), 16777619); return rng(hash >>> 0); }
  function build(): void { const r = wrap.getBoundingClientRect(); const w = Math.max(95, Math.floor(r.width / 4)); const h = Math.max(64, Math.floor((r.height || 420) / 4)); canvas.width = Math.max(1, Math.round(r.width)); canvas.height = Math.max(1, Math.round(r.height || 420)); field.width = w; field.height = h; pixels = fc!.createImageData(w, h); sim = new SandTerrarium(w, h); plant(); }
  function plant(): void { seedNo++; random = randomFor(seedNo); sim.seed(random); watcher.reset(); line.textContent = t('garden.st.seeded', { n: seedNo }); }
  function draw(stats: TerrariumStats): void { const data = pixels.data; for (let i = 0, p = 0; i < sim.cells.length; i++, p += 4) { const material = sim.cells[i]; const color = COLORS[material]; const flicker = material === Material.Fire ? (sim.age[i] % 3) * 18 : 0; data[p] = Math.min(255, color[0] + flicker); data[p + 1] = color[1]; data[p + 2] = color[2]; data[p + 3] = material === Material.Smoke ? 190 : 255; } fc!.putImageData(pixels, 0, 0); c.imageSmoothingEnabled = false; c.drawImage(field, 0, 0, canvas.width, canvas.height); stepEl.textContent = t('garden.st.step', { n: stats.step }); }
  function frame(): void { raf = requestAnimationFrame(frame); if (paused) return; let stats = sim.step(random); stats = sim.step(random); const event = watcher.observe(stats); if (event) line.textContent = t(`garden.st.event.${event}`, { n: stats.step }); draw(stats); if (stats.step >= 6000) plant(); }
  reseed.onclick = plant; pause.onclick = () => { paused = !paused; pause.setAttribute('aria-pressed', String(paused)); pause.textContent = t(paused ? 'garden.resume' : 'garden.pause'); }; reseed.textContent = t('garden.reseed'); pause.textContent = t('garden.pause'); name.textContent = t('garden.st.name'); code.textContent = t('garden.st.code'); hint.textContent = t('garden.st.hint'); build(); line.textContent = t('garden.st.today'); raf = requestAnimationFrame(frame);
  const ro = new ResizeObserver(() => { const r = wrap.getBoundingClientRect(); const w = Math.max(95, Math.floor(r.width / 4)); const h = Math.max(64, Math.floor((r.height || 420) / 4)); if (w !== sim.w || h !== sim.h) build(); }); ro.observe(wrap); Toolbox.onDispose?.(() => { if (raf !== undefined) cancelAnimationFrame(raf); ro.disconnect(); });
}

