/* 자동 생성 — `node scripts/gen-core-tools.mjs`. 손으로 고치지 마라. */
/* 「무엇을 부를 수 있나」만 든 가벼운 표 + 알맹이를 그때 받는 손. 정적 표(registry.generated)와
   달리 이 파일은 알맹이를 끌고 오지 않는다 — 묶어 쓰기가 이걸 쓴다. */
import type { ToolRunner } from './types';

export const CORE_OPS: Record<string, string[]> = {
  apidiff: ["compare"],
  apitest: ["list","example","default"],
  base64: ["encode","decode"],
  bgremove: ["describe"],
  birth: ["info"],
  bizno: ["check"],
  bundlemap: ["summary"],
  certview: ["read"],
  chain: ["run"],
  charconv: ["width","roman","han","pinyin","jamo"],
  charcount: ["count","fits"],
  codegraph: ["graph"],
  configconv: ["convert","detect"],
  csp: ["parse","review","build"],
  csvjson: ["toJson","toCsv"],
  curlkit: ["convert","parse"],
  daily: ["today"],
  dailycho: ["today"],
  dailytype: ["today"],
  datecalc: ["shift","between","dday"],
  diff: ["text","structure","merge"],
  docscan: ["describe"],
  dupphoto: ["describe"],
  dutchpay: ["settle"],
  encdetective: ["fix","explain"],
  epoch: ["toDate","toStamp"],
  erd: ["diagram","outline"],
  exif: ["read"],
  filehash: ["verify"],
  gitundo: ["steps","list"],
  grade: ["gpa","needed"],
  hangulkey: ["toKorean","toEnglish","auto"],
  hangultype: ["count","speed"],
  hashgen: ["text"],
  idphoto: ["specs","plan","sheet"],
  interest: ["deposit","saving","loan"],
  jamo: ["split","join","initials"],
  jqplay: ["query"],
  livecount: ["since","rate"],
  loan: ["schedule","compare"],
  logview: ["summary","filter"],
  mermaidlite: ["svg","check"],
  mesh3d: ["info"],
  mockdata: ["generate"],
  nettool: ["cidr","contains","split","port"],
  ocr: ["route","tidy"],
  passgen: ["strength"],
  payslip: ["monthly","yearly"],
  pdf2text: ["extract"],
  pdftool: ["merge","pages","extract","rotate"],
  pem: ["look"],
  photomap: ["describe"],
  prettyall: ["format","minify"],
  printkit: ["sheet"],
  protobuf: ["decode","encode"],
  qrgen: ["svg","wifi","contact"],
  regexplain: ["explain","railroad"],
  semver: ["explain","satisfies","overlap"],
  sqlfmt: ["format","dialect"],
  sshkey: ["read","convert"],
  tableconv: ["convert"],
  timecalc: ["shift","sum"],
  tts: ["split","estimate"],
  unicodex: ["scan","clean"],
  unitconv: ["convert","list"],
  uuidgen: ["generate"],
  vat: ["add","extract"],
  wordfreq: ["count"],
  workdays: ["after","between"],
  worldclock: ["convert","offset"],
  xmlfmt: ["format","minify","toJson"],
  ziptool: ["create","list","extract"],
};

type Loaded = { run: ToolRunner };

/** 그 도구의 알맹이를 **그때** 받아 온다. 같은 것을 두 번 받지는 않는다(브라우저가 묶음을 캐시한다). */
export const CORE_LOADERS: Record<string, () => Promise<Loaded>> = {
  apidiff: () => import('./apidiff').then((m) => ({ run: m.run })),
  apitest: () => import('./apitest').then((m) => ({ run: m.run })),
  base64: () => import('./base64').then((m) => ({ run: m.run })),
  bgremove: () => import('./bgremove').then((m) => ({ run: m.run })),
  birth: () => import('./birth').then((m) => ({ run: m.run })),
  bizno: () => import('./bizno').then((m) => ({ run: m.run })),
  bundlemap: () => import('./bundlemap').then((m) => ({ run: m.run })),
  certview: () => import('./certview').then((m) => ({ run: m.run })),
  chain: () => import('./chain').then((m) => ({ run: m.run })),
  charconv: () => import('./charconv').then((m) => ({ run: m.run })),
  charcount: () => import('./charcount').then((m) => ({ run: m.run })),
  codegraph: () => import('./codegraph').then((m) => ({ run: m.run })),
  configconv: () => import('./configconv').then((m) => ({ run: m.run })),
  csp: () => import('./csp').then((m) => ({ run: m.run })),
  csvjson: () => import('./csvjson').then((m) => ({ run: m.run })),
  curlkit: () => import('./curlkit').then((m) => ({ run: m.run })),
  daily: () => import('./daily').then((m) => ({ run: m.run })),
  dailycho: () => import('./dailycho').then((m) => ({ run: m.run })),
  dailytype: () => import('./dailytype').then((m) => ({ run: m.run })),
  datecalc: () => import('./datecalc').then((m) => ({ run: m.run })),
  diff: () => import('./diff').then((m) => ({ run: m.run })),
  docscan: () => import('./docscan').then((m) => ({ run: m.run })),
  dupphoto: () => import('./dupphoto').then((m) => ({ run: m.run })),
  dutchpay: () => import('./dutchpay').then((m) => ({ run: m.run })),
  encdetective: () => import('./encdetective').then((m) => ({ run: m.run })),
  epoch: () => import('./epoch').then((m) => ({ run: m.run })),
  erd: () => import('./erd').then((m) => ({ run: m.run })),
  exif: () => import('./exif').then((m) => ({ run: m.run })),
  filehash: () => import('./filehash').then((m) => ({ run: m.run })),
  gitundo: () => import('./gitundo').then((m) => ({ run: m.run })),
  grade: () => import('./grade').then((m) => ({ run: m.run })),
  hangulkey: () => import('./hangulkey').then((m) => ({ run: m.run })),
  hangultype: () => import('./hangultype').then((m) => ({ run: m.run })),
  hashgen: () => import('./hashgen').then((m) => ({ run: m.run })),
  idphoto: () => import('./idphoto').then((m) => ({ run: m.run })),
  interest: () => import('./interest').then((m) => ({ run: m.run })),
  jamo: () => import('./jamo').then((m) => ({ run: m.run })),
  jqplay: () => import('./jqplay').then((m) => ({ run: m.run })),
  livecount: () => import('./livecount').then((m) => ({ run: m.run })),
  loan: () => import('./loan').then((m) => ({ run: m.run })),
  logview: () => import('./logview').then((m) => ({ run: m.run })),
  mermaidlite: () => import('./mermaidlite').then((m) => ({ run: m.run })),
  mesh3d: () => import('./mesh3d').then((m) => ({ run: m.run })),
  mockdata: () => import('./mockdata').then((m) => ({ run: m.run })),
  nettool: () => import('./nettool').then((m) => ({ run: m.run })),
  ocr: () => import('./ocr').then((m) => ({ run: m.run })),
  passgen: () => import('./passgen').then((m) => ({ run: m.run })),
  payslip: () => import('./payslip').then((m) => ({ run: m.run })),
  pdf2text: () => import('./pdf2text').then((m) => ({ run: m.run })),
  pdftool: () => import('./pdftool').then((m) => ({ run: m.run })),
  pem: () => import('./pem').then((m) => ({ run: m.run })),
  photomap: () => import('./photomap').then((m) => ({ run: m.run })),
  prettyall: () => import('./prettyall').then((m) => ({ run: m.run })),
  printkit: () => import('./printkit').then((m) => ({ run: m.run })),
  protobuf: () => import('./protobuf').then((m) => ({ run: m.run })),
  qrgen: () => import('./qrgen').then((m) => ({ run: m.run })),
  regexplain: () => import('./regexplain').then((m) => ({ run: m.run })),
  semver: () => import('./semver').then((m) => ({ run: m.run })),
  sqlfmt: () => import('./sqlfmt').then((m) => ({ run: m.run })),
  sshkey: () => import('./sshkey').then((m) => ({ run: m.run })),
  tableconv: () => import('./tableconv').then((m) => ({ run: m.run })),
  timecalc: () => import('./timecalc').then((m) => ({ run: m.run })),
  tts: () => import('./tts').then((m) => ({ run: m.run })),
  unicodex: () => import('./unicodex').then((m) => ({ run: m.run })),
  unitconv: () => import('./unitconv').then((m) => ({ run: m.run })),
  uuidgen: () => import('./uuidgen').then((m) => ({ run: m.run })),
  vat: () => import('./vat').then((m) => ({ run: m.run })),
  wordfreq: () => import('./wordfreq').then((m) => ({ run: m.run })),
  workdays: () => import('./workdays').then((m) => ({ run: m.run })),
  worldclock: () => import('./worldclock').then((m) => ({ run: m.run })),
  xmlfmt: () => import('./xmlfmt').then((m) => ({ run: m.run })),
  ziptool: () => import('./ziptool').then((m) => ({ run: m.run })),
};
